### ISSUE TITLE
read gists

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartpad_ui#37]

**Comment by devoncarew** [comment]
1/2 of this is some server redirects / url handling, so that `/12345678` serves the app frontend, instead of trying to serve some file from `/12345678`.

@lukechurch

**Comment by devoncarew** [comment]
`dartpad-dev.appspot.com/12345678` would be a great url scheme - very short - but I don't know how we can be certain to recognize a gist ID in that top-level name. `dartpad-dev.appspot.com/gist/12345678` would also work, and be easier to recognize, but a little more verbose.

**Comment by devoncarew** [comment]
IDs seem long (a373f076801e512308c3) and lower case hexadecimal.

Older ones seem shorter, and just numeric (6893556).

**Comment by lukechurch** [comment]
I've put together a little demo here: 

http://gist-demo.dartpad-dev.appspot.com/432342/style.css
Please can you have a play and see if this is the kind of thing you were thinking of?

Using positional arguments as the way of defining the gist does lead to some slightly whacky behaviours, such as

http://gist-demo.dartpad-dev.appspot.com/style.css

interprets 'style.css' as the name of the gist and serves back index.html.

So I'm leaning a little more downwards the more explicit behaviour of /gist/id

What do you think?

**Comment by devoncarew** [comment]
Thanks for working on this! Let's talk at the standup.

**Comment by lukechurch** [comment]
Server now behaves as I think we want. I think we just need to adjust the client now

**Comment by devoncarew** [comment]
We have this now -
