### ISSUE TITLE
Need to fetch fonts over HTTPS

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dartpad_ui#50]
Otherwise we get the browser blocking Non-SSL loads

**Comment by devoncarew** [comment]
See https://github.com/dart-lang/dartpad_ui/commit/ebd9568c7f05a430ad346c4d864a5d44f4229573 - we need to repush the current code base.

**Comment by lukechurch** [comment]
Pushed. But I'm still seeing:

 "Mixed Content: The page at 'https://dartpad.googleplex.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto'. This request has been blocked; the content must be served over HTTPS."

**Comment by devoncarew** [comment]
Hmm, I'll investigate.

**Comment by devoncarew** [comment]
kk, I'll just change this to explicit https: references.
